# 이 name은 내가 정할 수 있는 이름이다.
name: hanbok-server
#  master branch로 pull_request 할때 실행되도록 한다.
on: push

jobs:
  build-and-test: # 내가 알아서 정할 수 있다.

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18]

    steps:
      - name: Checking out repository code
        uses: actions/checkout@v2 # git clone 하는 action 예를 들어서 npm 에서 install 하는거랑 비슷
      
      - name: Use Node.js ${{ matrix.node-version }}
          # npm install / 패키지이름 github action에서 사용하기 때문에 actions/ 
        uses: actions/setup-node@v1
        with:
        node-version: ${{ matrix.node-version }}

      - run: npm install
    # - run: npm run build --if-present
      - run: npm test