name: Build docker image and publish on docker hub
# 이 on 행동을 했을 경우에 아래 jobs trigger 가 시작된다.
# master에 push 가 되면 merge가 되면서 push 가 된다.
on: workflow_dispatch
  # 이렇게 하면 선택해서 돌릴수도 있고 master로 push를 할때 자동으로 돌릴 수 있음
  # workflow_dispatch:
  # push:
  #   branches:
  #   - master

jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      #  앞서 build-and-test 단계에서 해줬지만 한번더 새로 checkout을 해야한다.
      - name: Checking out repository code
        uses: actions/checkout@v2 # git clone 하는 action 예를 들어서 npm 에서 install 하는거랑 비슷
      
      # https://github.com/marketplace/actions/build-and-push-docker-images 그대로 복붙하면됨
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # git hub 에 해당 리파지토리에 setting에서 설정할 수 있다. 이거 내 아이디 magicq6265 이다.
          password: ${{ secrets.DOCKERHUB_TOKEN }} # 위와 같이 설정을 해주는데 token은 docker hub에서 받을 수 있다.

      - name: Setting environment variables
        run: |
          chmod +x ./scripts/set-env.sh
          ./scripts/set-env.sh
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          PORT: ${{secrets.PORT}}
          PAYPAL_CLIENT_ID: ${{secrets.PAYPAL_CLIENT_ID}}
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
          EMAIL: ${{secrets.EMAIL}}
          EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
          MONGODB_URL: ${{secrets.MONGODB_URL}}

      - name: Building docker image
        run: make build

      - name: Publishing docker image
        run: make push